name: Lint Code Base
on: 
  push:
    branches-ignore: [dev]
  pull_request:
    branches: [dev]
    
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: Install modules
      run: npm ci
    - name: Lint all files
      run: npm run lint:check
    - name: Strict lint for changes
      run: npm run lint-changes:check
